name: New Feature - Request a new feature
description: Suggest an idea for improving our solution.
title: "[VERB] <your issue subject here>"
labels: ['feature-request']
body:
  - type: textarea
    id: feature_summary
    attributes:
      label: What is this feature about?
      description: A clear and concise description of what the feature or problem is. Ex. As an end-user, I would like to be able to [...]
      placeholder: As a <type of user/customer>, I want <an action/business need>, So that <a benefit/a business value>
    validations:
      required: true
  - type: textarea
    id: detailed_description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. You may use bullets to capture your ideas more clearly.
    validations:
      required: true
  - type: textarea
    id: alternatives_considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
